// Extracts clean prose from docs/curriculum.txt into src/data/corpus.ts
// for the in-browser n-gram language model on the home page.
import fs from "node:fs";

const text = fs.readFileSync("docs/curriculum.txt", "utf8");
const keep = [];

for (const raw of text.split(/\r?\n/)) {
  const t = raw.trim();
  if (!t) continue;
  if (/^Automation with Generative AI/i.test(t)) continue;
  if (/^Page \d+/i.test(t)) continue;
  if (/^MODULE \d/i.test(t)) continue;
  if (/^CURRICULUM DOCUMENT/i.test(t)) continue;
  if (/^TOTAL HOURS/i.test(t)) continue;
  if (/^\d+\s*$/.test(t)) continue;
  if (/^#\s*Module Hours/i.test(t)) continue;
  const isBullet = t.startsWith("•");
  const body = t.replace(/^•\s*/, "");
  // bullets are sentence fragments — terminate them so the model
  // learns them as complete statements
  keep.push(isBullet ? `${body} .` : body);
}

const clean = keep
  .join(" ")
  .toLowerCase()
  .replace(/['’]/g, "")
  .replace(/[—–]/g, " ")
  .replace(/\./g, " . ")
  .replace(/[^a-z0-9. ]/g, " ")
  .replace(/\s+/g, " ")
  .trim();

fs.writeFileSync(
  "src/data/corpus.ts",
  `// Generated by scripts/build-corpus.mjs from docs/curriculum.txt — do not edit by hand.
// The curriculum's own prose, cleaned and tokenized, used as training data
// for the tiny n-gram language model in LlmDiagram.
export const corpus =
  ${JSON.stringify(clean)};
`,
);

console.log(
  `corpus.ts written: ${clean.length} chars, ~${clean.split(" ").length} tokens`,
);
